### ISSUE TITLE
Why have to click the button twice to attach successfully?

### ISSUE THREAD

**Issue by diegobona** [boytchev/mannequin.js#21]
If I put the attach() function into the callback function of the button click event,have to click the button twice to attach successfully:

```
$("#teststickButton").click(function() {  
    stick = new THREE.Mesh(
          new THREE.CylinderGeometry(0.5, 0.5, 30, 16),
          new THREE.MeshPhongMaterial({color: 'crimson', shininess: 200})
          );
          stick.castShadow = true;  
          model.l_fingers.attach(stick);
});
```

**Comment by boytchev** [comment]
Hi -

Honestly, I do not know. The code by itself looks fine. There might be many reasons, like:

- another part of your code is interfering with mannequin.js
- you are using some forked, unoriginal manequin.js
- the Three.js version is different from the one that manneqiin.js uses

When I try a clean example, it works fine. Here is my test of using `attach` from a callback function linked to the `onClick` event of a button:

https://boytchev.github.io/mannequin.js/examples/qa-attach-from-button.html

- Pavel

**Comment by diegobona** [comment]
> Hi -
> 
> Honestly, I do not know. The code by itself looks fine. There might be many reasons, like:
> 
> * another part of your code is interfering with mannequin.js
> * you are using some forked, unoriginal manequin.js
> * the Three.js version is different from the one that manneqiin.js uses
> 
> When I try a clean example, it works fine. Here is my test of using `attach` from a callback function linked to the `onClick` event of a button:
> 
> https://boytchev.github.io/mannequin.js/examples/qa-attach-from-button.html
> 
> * Pavel

Add     renderer.render(scene, camera);         at the end to solve it，
thank  you！

**Comment by boytchev** [comment]
Hi –

I still cannot reproduce the issue. If `renderer.render` solves the problem, then the attached object is created and attached, but the canvas is nor redrawn. Would it be OK to add `renderer.render` in your callback right after the call to `attach`?

– Pavel

**Comment by diegobona** [comment]
> Hi –
> 
> I still cannot reproduce the issue. If `renderer.render` solves the problem, then the attached object is created and attached, but the canvas is nor redrawn. Would it be OK to add `renderer.render` in your callback right after the call to `attach`?
> 
> – Pavel

it's work, just like this:

`function addStick(joint){
  stick = new THREE.Mesh(
  new THREE.CylinderGeometry(0.5, 0.5, 30, 16),
  new THREE.MeshPhongMaterial({color: 'crimson', shininess: 200})
  );
  stick.castShadow = true;
  stick.rotateX( Math.PI / 2 ); 
  stick.position.y = joint.y+1;
  stick.position.x = joint.x-0.5;
  stick.position.z = joint.z-22;
  joint.attach(stick);
  renderer.render(scene, camera);
  return stick;
}

$("#toggle-stick-l").change(function() {  
    if(this.checked) {
        let stick=addStick(model.l_fingers);  
    } else {
        stick.material.visible=false;
        renderer.render(scene, camera);
    }
});

`
