### ISSUE TITLE
About customizing models

### ISSUE THREAD

**Issue by diegobona** [boytchev/mannequin.js#23]
Hello, Maybe my last question：
 I saw https://setpose.com，there is a "detailed model" on it. Is this customized by the developer? Is its rotation  can implemented by mannequin.js? Including how it has five clear fingers and can rotate them?

**Comment by boytchev** [comment]
Hi –

I'm unrelated to setpose.com.

As far as I know setpose.com uses mannequin.js as a foundation and adds additional features on top of it. I have not seen the detailed model. My guess is that it is added by the setpose.com developer. If setpose.com has the features that you need, why don't you use setpose.com?

I'll add detailed models to my todo list.

– Pavel

**Comment by diegobona** [comment]
I'm looking forward to it!! You are great!
