### ISSUE TITLE
Detailed model

### ISSUE THREAD

**Issue by boytchev** [boytchev/mannequin.js#24]
Add a more detailed model (e.g. individual fingers).

**Comment by diegobona** [comment]
I'm looking forward to it!!   I want to try it for myself first: if I create a 3D body model in blender, do I name all its body parts consistent with the definition in the "names" array, and then create a class in mannequin.js to inherit the "mannequin" class, and then I can operate on it?

**Comment by diegobona** [comment]
Dude, well done ! have you made any progress？detailed model and multiple figures.

**Comment by boytchev** [comment]
Hi –
I'll resume working on it from Monday, Dec 26th. As explained here https://github.com/boytchev/mannequin.js/issues/25#issuecomment-1336408427 I did not changed anything in mannequin, because it could mess up with homework assignments.
– Pavel

**Comment by boytchev** [comment]
Hi –
Multiple figures are now supported in the Posture Editor. I do not like the UI right now, but the functionality is there. I'll think about the UI and how to make it less irritating. (Individual fingers are not implemented yet)
– Pavel

**Comment by boytchev** [comment]
@diegobona –

Fingers are implemented, but the new code is not uploaded yet. Many of the examples use the old topology, and I have to fixed them before uploading to GitHub.

Here is a snapshot of how fingers look like.

![image](https://user-images.githubusercontent.com/70705048/210367468-a3fa0a62-5620-4f58-8a24-be3b2e0377a7.png)

– Pavel

**Comment by diegobona** [comment]
> 

That's great! thank you

**Comment by boytchev** [comment]
Detailed mannequin with individual hand fingers is uploaded. Issue is closed. Documentation will be updated soon.
