### ISSUE TITLE
2D Posture Data

### ISSUE THREAD

**Issue by danvpop1** [boytchev/mannequin.js#31]
Hello, 
When I use the get posture method, I get relative positions values and the vectors are not consistently populated with what seems like positional data. Where can I recover the joint positions in world space? My goal is to get the 3D world space joint positions, and project them into 2D coordinates in image space. 
Thanks!

**Comment by boytchev** [comment]
The [`posture`](https://boytchev.github.io/mannequin.js/#working-with-postures) property returns a collection of angles in joints. It is used later on to recreate a body posture. The joint positions in world space are not included in the posture, as they are not a primary data, but derivatives.

To get the global 3D coordinates of a joint use its ['point'](https://boytchev.github.io/mannequin.js/#global-position) method. For example `person.l_ankle.point(0,0,0)` should return the world space position of the left ankle of `person`.
