### ISSUE TITLE
Scale torso

### ISSUE THREAD

**Issue by adnanafzal565** [boytchev/mannequin.js#34]
First of all, Great library, thanks.

How to scale waist and chest of man ?

**Comment by boytchev** [comment]
Scaling is available when you use mannequin.js and manually control the figures. The online posture editor has no functionality to modify body sizes.

Here is a demo how to scale the torso (and keep other body parts the same):

https://boytchev.github.io/mannequin.js/examples/qa-custom-torso-sizes.html

See lines 24-27 (*s* is the scaling factor):
```
man.torso.scale.set(s, s, s);
man.l_arm.scale.set(1/s, 1/s, 1/s);
man.r_arm.scale.set(1/s, 1/s, 1/s);
man.neck.scale.set(1/s, 1/s, 1/s);
```
