### ISSUE TITLE
How to get the ear and eye coordinates?

### ISSUE THREAD

**Issue by boomsi** [boytchev/mannequin.js#35]
As the title.
Is there any way to get the coordinates of the eyes and ears of the human head.

**Comment by boomsi** [comment]
I see the Head class, but not find the eyes or ears attributes

**Comment by boytchev** [comment]
The eyes and the ears do not exist as separate objects. You can get their global coordinates with the method [.point](https://boytchev.github.io/mannequin.js/#global-position). If you want to use own objects for eyes or ears and place them over the default eyes or ears, you can use the method [.attach](https://boytchev.github.io/mannequin.js/#custom-body-parts).

For both methods you need the local coordinates of the eyes and the ears (i.e. the coordinates in respect to the head). They are approximately:
* right eye `(1.6,2.6,1.1)`
* left eye `(1.6,2.6,-1.1)`
* right ear `(0,2.1,3)`
* left ear `(0,2.1,-3)`

This example demonstrates custom eyes:

[https://boytchev.github.io/mannequin.js/examples/qa-eyes-and-ears.html](https://boytchev.github.io/mannequin.js/examples/qa-eyes-and-ears.html)

[![image](https://github.com/boytchev/mannequin.js/assets/70705048/aad014a6-d0d8-4814-9d86-29fb00c63693)](https://boytchev.github.io/mannequin.js/examples/qa-eyes-and-ears.html)
