### ISSUE TITLE
Change Size Of Body Parts

### ISSUE THREAD

**Issue by mohamadkenway** [boytchev/mannequin.js#36]
Hello to legend developer(s)

how we can change of body size like hip or arms and in order to make fat guy or thin guy .... ?

**Comment by boytchev** [comment]
Maybe this example will help you?

[https://boytchev.github.io/mannequin.js/docs/qa-custom-torso-sizes.html](https://boytchev.github.io/mannequin.js/docs/qa-custom-torso-sizes.html)

If scaling is not sufficient, you can hide the body part and put your custom body part instead.
