### ISSUE TITLE
What is the function of this library?

### ISSUE THREAD

**Issue by xuanyanwow** [boytchev/mannequin.js#8]
I'm sorry I may have mentioned a useless issue. I happened to see this class library in github. Although the document provides a lot of examples, I still don't understand the specific application scenario of this class library. Is it used to make games?

**Comment by boytchev** [comment]
The initial and primary use of mannequin.js is in the course "Fundamentals of Computer Graphics". However, the library could be used in other scenarios, especially if someone needs a 3D character that can be animated programmatically with vanilla JavaScript.

PS. I'll enable the Discussion  tab.
